title: disjfa.github.io
email: disjfa@disjfa.nl
description: >
  Project website. All my projects bundled into one, here you can check out my projects and check what you want to use maybe.
  I like to use css, javascript, npm, bootstrap, symfony, jekyll and such.
baseurl: ""
url: "https://disjfa.github.io"
twitter_username: disjfa
github_username:  disjfa

markdown: kramdown
host: 0.0.0.0

portfolio_dir: "projects"
related_project_keys: ["category", "technology"]
related_min_common: 0.7

google_analytics: UA-83598448-1

paginate: 15
paginate_path: "/blog/page:num/"

collections:
  category:
    output: true

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

plugins:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - assets
  - LICENSE
  - package.json
  - package-lock.json
  - README.md
  - webpack.config.js
  - gulpfile.js
